### ISSUE TITLE
React Native 开发环境搭建及运行第一个应用程序

### ISSUE THREAD

**Issue by uniquexiaobai** [uniquexiaobai/blog#6]
[React Native](http://facebook.github.io/react-native/) 是 Facebook 开源的使用 JavaScript 开发原生 Android、IOS 应用的框架。
它将你的 JavaScript 代码解析成真正原生的 UI 组件，并根据平台的差异渲染到相应平台上，使用 React Native 即可以开发出拥有 Native 的良好人机交互体验的应用，又提升了开发效率，降低了开发移动APP的门槛。更详细的关于 React Native 的介绍可以参考下面两篇文章：
- [如何评价 React Native](https://www.zhihu.com/question/27852694)
- [H5、React Native、Native应用对比分析](https://my.oschina.net/vczero/blog/597980)

本文简单介绍 React Native 针对 Android 和 IOS 平台的环境配置及运行第一个 React Native 应用。
## Android平台
1. 下载并安装 [Node.js](https://nodejs.org/en/)
2. 下载并安装 [Android Studio](https://developer.android.com/studio/index.html)（需科学上网），并配置 Android 的开发环境，如安装 [jdk](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html) 、Android模拟器等
3. 安装 React Native 命令行工具，它用于创建、初始化、更新项目、打包等任务（`$` 代表后面的命令需要在相应的终端下执行）
```
$ npm install -g react-native-cli
```
4. 创建并初始化一个名为 Hello 的项目
```
$ react-native init Hello
```
5. 连接 Android 手机，或打开 Android 虚拟机，运行 Hello 项目
```
$ react-native run-android
```
6. 运行截图：

![android](https://cloud.githubusercontent.com/assets/12796673/20028501/80dc3b86-a36e-11e6-84c2-90d9d1c80336.png)

## IOS平台
1. 下载并安装 [Node.js](https://nodejs.org/en/download/)
2. 下载并安装 [Xcode](http://blog.csdn.net/wangjia55/article/details/50474965)（外部各版本下载地址），并配置 iPhone 模拟器等 IOS 开发环境
3. 安装 React Native 命令行工具<br>
```
$ npm install -g react-native-cli
```
4. 创建并初始化一个名为 Hello 的项目<br>
```
$ react-native init Hello
```
5. 双击 Hello/ios/Hello.xcodeproj 文件，打开 Xcode ，点击 Xcode 中的运行按钮

6. 运行截图：

![ios](https://cloud.githubusercontent.com/assets/12796673/20028499/7a836d04-a36e-11e6-9160-ec43e19f1483.png)

**Comment by chuxue2005** [comment]
楼主的demo不错，看楼主在踩微信小程序的坑，踩完能否写篇文章分享一下

**Comment by uniquexiaobai** [comment]
业余踩一下，小程序太火！

**Comment by windstormeye** [comment]
哇塞！！！第一次知道Issues也能写博客，改天瞅一眼。。。学长你的讲座很棒噢，ppt做的很酷炫，能不能教教这种酷炫的效果怎么做到的？

**Comment by uniquexiaobai** [comment]
Issues写博客有利也有弊，ppt 用的 [Reveal](https://github.com/hakimel/reveal.js)
